version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5673:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 15s
      retries: 3

  notification-service:
    build:
      context: ./services/Tasco.NotificationService
      dockerfile: Tasco.NotificationService.Worker/Dockerfile
    container_name: notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Email SMTP Configuration
      - Email__Host=smtp.gmail.com
      - Email__Port=587
      - Email__SystemName=Tasco
      - Email__Sender=moneymind392@gmail.com
      - Email__Password=jhxa qrsl bcru ihra
      # RabbitMQ Configuration
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__ExchangeName=notifications
      - RabbitMQ__QueueName=notification-queue
      - RabbitMQ__RoutingKey=notification
      - RabbitMQ__Durable=true
      - RabbitMQ__AutoDelete=false
      - RabbitMQ__Exclusive=false
      - RabbitMQ__RetryCount=3
      - RabbitMQ__RetryDelay=00:00:05
    networks:
      - app-network

networks:
  app-network:
    driver: bridge